version: '3'
services:
  redis:
    image: 'redis:3.0-alpine'
    environment:
      - RACK_ENV=development
      - type=database
    ports:
      - "6300:6379"
      - "6400:22"

  nats:
    image: nats
    labels:
      - "traefik.backend=web"
      - "traefik.port=80"

  busybox:
    image: 'busybox'
    command: tail -fn10 .dockerenv
    restart: unless-stopped
